#!/usr/bin/env python3
"""Build a portable Digital certificate HTML with JSX inlined (works via file://)."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "employee-certificate" / "project"
SOURCE = PROJECT / "Employee Certificate - Digital.html"
OUTPUT = PROJECT / "Employee Certificate - Portable.html"

JSX_FILES = ("tweaks-panel.jsx", "digital-cert.jsx")


def main() -> None:
    html = SOURCE.read_text(encoding="utf-8")
    for name in JSX_FILES:
        jsx = (PROJECT / name).read_text(encoding="utf-8")
        needle = f'<script type="text/babel" src="{name}"></script>'
        if needle not in html:
            raise SystemExit(f"Missing script tag for {name}")
        html = html.replace(
            needle,
            f'<script type="text/babel" data-source="{name}">\n{jsx}\n</script>',
        )
    banner = (
        "<!-- Generated by scripts/build-portable.py — do not edit; "
        "edit Digital.html / *.jsx and rebuild. -->\n"
    )
    if banner.strip() not in html:
        html = html.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n{banner}", 1)
    OUTPUT.write_text(html, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
